SEC_CAP:
  COLUMN_MAPPING:
    CURNCY_CD: CURRENCY_CODE
  UNIQUE_KEY:
    - SEC_ID
  COLUMNS_TO_MATCH:
    - CURNCY_CD
    - FEED_SRC_CD
    - INDEX_PROVIDER
    - CAP_DT
    - SEC_CAP
    - MODIFIED_YN